### PR TITLE
Button component

### PR DESCRIPTION
**Pull request by aliv314**
Added button component for sign-in/sign-up with hover on-click functionality.
Test the Button by quickly importing it to <App> component.

Added colors to the Tailwind theme file. This needs review from the group as it's a global file.
Font and text customization yet to be added to tailwind theme file.

### CODE REVIEW

**Comment by LEPII** [comment]
I think you might have a merge conflit with https://github.com/grammerjam/tg-main/pull/20 since it seems that you both tried to create the color theme in the tailwind config file but everything looks good.

**Comment by aliv314** [comment]
I will merge #20 before changing this button.

**Comment by jluiscool** [comment]
image

getting linting errors on the button component.

**Comment by aliv314** [comment]
Thank you for the feedback. I haven't worked with a linter before, but I'll research and do my best to fix it ASAP.

**Pull request merged**
