### PR TITLE
Feature/signup

### PR DESCRIPTION
**Pull request by avecc003**
- Completed UI to Figma specification
- Successfully sent a verification email when testing, but missing clerk credentials to verify that registration worked.
- Needs further testing for rerouting to login page.

Hours: 8

### CODE REVIEW

**Comment by jluiscool** [comment]
I merged the routes in App from develop into this branch and changed the link from the login page to point to /signup instead of /sign-up.

Fixes pending:
Padding in mobile  between the form and page missing. (checked 320px width and there's no padding)
No error message when submitting 'Create Account' if fields are empty
Active form input has an outline, should just be underline
Form caret should be red
Logo and Form spacing needs to be modified to Figma mockup

Ale please pull this branch from origin since its updated with develop

**Comment by avecc003** [comment]
Thank you for the feedback Jose. I'll work on it right away.

**Comment by avecc003** [comment]
I think I've addressed every error that you've outlined in your original feedback. Please give it a second look and let me know if I should change anything else. Thank you.

**Comment by jluiscool** [comment]
Looks good Ale, ready to merge!

**Comment by avecc003** [comment]
Thank you, Jose. I'll close this PR and merge into develop.

**Pull request closed without merging**
