### PR TITLE
Patch/frontend adjustments

### PR DESCRIPTION
**Pull request by avecc003**
- Adjusted the sizing of the trending cards 
- Swapped recommended and trending titles

### CODE REVIEW

**Comment by avecc003** [comment]
- Removed autocorrect squiggly lines.
- Gave thumbnails aspect ratio for consistent sizing.

**Comment by jluiscool** [comment]
Hey Ale, everything looks good except the tablet view:

The navbar and searchbar aren't fixed to the top.
Also in tablet view, could you fix the MediaContainer right padding? It's 16px atm and should be 24px

**Comment by avecc003** [comment]
Finished up the last changes and fixed on tablet. Let me know what you think.

**Comment by jluiscool** [comment]
Looks good Ale, going to merge it.

**Pull request merged**
